# Generated by Django 4.0.4 on 2022-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatization',
            name='auto_number',
            field=models.IntegerField(default=0, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automatization',
            name='delta',
            field=models.PositiveIntegerField(verbose_name='После предыдущего сообщения отослать через '),
        ),
    ]
